version: "3"
volumes:
  pgdata:
  static_files:
services:
  python: &python
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=studypunch.settings.prod
    volumes:
      - ./app:/app
      - static_files:/static_files
    ports:
      - 8001:8001
    depends_on:
      - postgres
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_USER: 'studypunch'
      POSTGRES_DB: 'studypunch'
      POSTGRES_PASSWORD: 'studypunch'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432